<a href="https://colab.research.google.com/github/julienessan/Gomycode_Cours_Data_Sciences/blob/main/Checkpoint_Nettoyage_data_pandas_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Checkpoint: Nettoyage et transformation des données avec Pandas**

**Objectif**

Renforcer la maîtrise de la manipulation des DataFrames pandas en créant et en interrogeant des ensembles de données en utilisant iloc pour les sélections basées sur l'index et loc pour les filtrages basés sur les étiquettes.

In [1]:
import pandas as pd

In [4]:
data = {'Name' : ['John', 'Mary', 'Bob', 'Sarah', 'Tom', 'Lisa'],
        'Department' : ['IT', 'Marketing', 'Sales', 'IT', 'Finance', 'Marketing'],
        'Age' : [30, 40, 25, 35, 45, 28],
        "Sexe" : ['Homme', 'Femme', 'Homme', 'Femme', 'Homme', 'Femme'],
        'Salaire' : [50000, 60000, 45000, 55000, 70000, 55000],
        'Expérience' : [3, 7, 2, 5, 10, 4]}
employee_df = pd.DataFrame(data)
employee_df

    Name Department  Age   Sexe  Salaire  Expérience
0   John         IT   30  Homme    50000           3
1   Mary  Marketing   40  Femme    60000           7
2    Bob      Sales   25  Homme    45000           2
3  Sarah         IT   35  Femme    55000           5
4    Tom    Finance   45  Homme    70000          10
5   Lisa  Marketing   28  Femme    55000           4

In [5]:
#Utilisez la méthode iloc pour sélectionner les 3 premières lignes du dataframe.
employee_df.iloc[:3]

   Name Department  Age   Sexe  Salaire  Expérience
0  John         IT   30  Homme    50000           3
1  Mary  Marketing   40  Femme    60000           7
2   Bob      Sales   25  Homme    45000           2

In [6]:
# Utilisez la méthode loc pour sélectionner toutes les lignes où le département est "Marketing".
employee_df.loc[employee_df['Department'] == 'Marketing']

   Name Department  Age   Sexe  Salaire  Expérience
1  Mary  Marketing   40  Femme    60000           7
5  Lisa  Marketing   28  Femme    55000           4

In [7]:
#Utilisez la méthode iloc pour sélectionner les colonnes Age et Sexe pour les 4 premières lignes du dataframe.
employee_df.iloc[:4, 2:4]

   Age   Sexe
0   30  Homme
1   40  Femme
2   25  Homme
3   35  Femme

In [8]:
#Utilisez la méthode loc pour sélectionner les colonnes Salaire et Expérience pour toutes les lignes dont le sexe est "Male".
employee_df.loc[employee_df['Sexe'] == 'Homme', ['Salaire', 'Expérience']]

   Salaire  Expérience
0    50000           3
2    45000           2
4    70000          10